### ISSUE TITLE
getUrlForService can return incorrect URL

### ISSUE THREAD

**Issue by ThomWright** [momentumft/navy#58]
From my understanding, a URL is registered in the nginx proxy for each service running, something like `http://myservicename.dev.127.0.0.1.xip.io`.

When `getUrlForService` is invoked, it returns something of the same form.

The problem arises when we change, for example, `xip` for `nip`. nginx can have services registered with `xip` URLs, and `getUrlForService` will return `nip` URLs which won't work.

As I see it there are two possible solutions here:

1. Make nginx match only on the `<servicename>.<navyname>` part of the url
2. Make `getUrlForService` look up the url it has registered with nginx for a given service, and return that, rather than assume it's used `xip` or `nip`.

**Comment by madjam002** [comment]
Why would nginx still have services registered with `xip` rather than `nip` if you've changed the domain?

I agree it would be better to lookup the URL from the nginx hosts file rather than just doing simple string concatenation, but it should always return the correct URL.

After changing the domain from `xip` to `nip`, you should do a `navy refresh-config` to make sure that all of the services launched are up to date.

**Comment by ThomWright** [comment]
We haven't moved everything over yet because we're still testing the release candidates, so some people have a mix of Navy 2 and 3 running globally and project locally.

So yes, it's only a problem if we have a mix of versions. But if we ever need to change this again then it would be good to have a robust system that won't break in the changeover period.

Hopefully then it could also not be considered to be a breaking change.

**Comment by tanuck** [comment]
Also if you do the following:

`navy launch a` and then `export NAVY_EXTERNAL_SUBDOMAIN=foo.com; navy launch b`, service `a` will now return a `foo.com` domain when doing `navy url a` even though it's virtual host in nginx has been configured for `nip`. Really `navy url` needs to use the container environment variables as its source of truth.

Possibly this logic needs to be broken out into a `getUrlForService` and `createUrlForService` functions.

**Comment by tanuck** [comment]
Solved by #59
